import { useApp } from "../context/AppContext";
import SDGBadge from "../components/ui/SDGBadge";
import { BarChart3, Globe, Award, TrendingUp, Users, Zap, CheckCircle2, HeartHandshake } from "lucide-react";

export default function ImpactDashboardPage() {
  const { sdgList, users, projects } = useApp();

  const impactMetrics = [
    { label: "Clean Water Monitored", value: "2.4M Liters", subtext: "Across 14 rural communities", color: "text-sky-400" },
    { label: "CO2 Offset Estimated", value: "340,000 Tons", subtext: "Via microgrids & canopy AI", color: "text-emerald-400" },
    { label: "Students Educated", value: "120,000+", subtext: "Through open EdTech portals", color: "text-rose-400" },
    { label: "Tech Hours Contributed", value: "48,500 Hrs", subtext: "By 1,240+ verified devs", color: "text-teal-400" }
  ];

  // Top impact contributors leaderboard
  const topUsers = [...users].sort((a, b) => b.impactPoints - a.impactPoints).slice(0, 5);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Header Banner */}
      <div className="glass-card rounded-3xl p-6 sm:p-8 border border-emerald-500/30 bg-gradient-to-r from-slate-950 via-emerald-950/30 to-slate-950 space-y-3">
        <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-wider">
          <BarChart3 className="w-4 h-4" />
          <span>Real-Time Environmental & Social Metrics</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black text-white">Global Impact Dashboard</h1>
        <p className="text-xs sm:text-sm text-slate-300 max-w-3xl leading-relaxed">
          Measuring the tangible real-world outcomes generated by software engineers, data scientists, and NGOs collaborating across the 17 UN Sustainable Development Goals.
        </p>
      </div>

      {/* Global Impact Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {impactMetrics.map((item, idx) => (
          <div key={idx} className="glass-card rounded-2xl p-6 border border-slate-800 space-y-2">
            <span className="text-xs text-slate-400 font-semibold block">{item.label}</span>
            <div className={`text-2xl sm:text-3xl font-black ${item.color}`}>{item.value}</div>
            <p className="text-[11px] text-slate-400">{item.subtext}</p>
          </div>
        ))}
      </div>

      {/* Main Grid: SDG Distribution & Top Leaderboard */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column (2 Cols): SDG Contribution Breakdown */}
        <div className="lg:col-span-2 glass-panel p-6 rounded-3xl border border-slate-800 space-y-6">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Globe className="w-5 h-5 text-emerald-400" />
              <span>Project Distribution by SDG Goal</span>
            </h3>
            <span className="text-xs text-slate-400 font-semibold">{projects.length} Total Projects</span>
          </div>

          <div className="space-y-4">
            {sdgList.slice(0, 10).map((sdg) => {
              const alignedCount = projects.filter((p) => p.sdgs.includes(sdg.id)).length;
              const percentage = Math.round((alignedCount / projects.length) * 100) || 15;
              return (
                <div key={sdg.id} className="space-y-1.5 text-xs">
                  <div className="flex items-center justify-between text-slate-200">
                    <div className="flex items-center gap-2">
                      <span
                        className="w-5 h-5 rounded text-[10px] font-black text-white flex items-center justify-center shrink-0"
                        style={{ backgroundColor: sdg.color }}
                      >
                        {sdg.number}
                      </span>
                      <span className="font-semibold">{sdg.title}</span>
                    </div>
                    <span className="text-emerald-400 font-bold">{alignedCount} Projects ({percentage}%)</span>
                  </div>
                  
                  <div className="w-full bg-slate-950 h-2 rounded-full overflow-hidden border border-slate-800">
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{ width: `${Math.max(8, percentage)}%`, backgroundColor: sdg.color }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column: Leaderboard of Top Contributors */}
        <div className="glass-panel p-6 rounded-3xl border border-slate-800 space-y-6">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Award className="w-5 h-5 text-amber-400" />
              <span>Top Impact Contributors</span>
            </h3>
            <span className="text-xs text-amber-400 font-bold">Leaderboard</span>
          </div>

          <div className="space-y-3">
            {topUsers.map((user, idx) => (
              <div key={user.id} className="p-3 rounded-2xl bg-slate-950 border border-slate-800 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <span className="w-6 text-center font-black text-xs text-slate-500">#{idx + 1}</span>
                  <img src={user.avatar} alt={user.name} className="w-9 h-9 rounded-xl object-cover" />
                  <div>
                    <h4 className="text-xs font-bold text-white">{user.name}</h4>
                    <p className="text-[10px] text-emerald-400">{user.role.split(' ')[0]}</p>
                  </div>
                </div>

                <div className="text-right">
                  <span className="text-xs font-black text-emerald-400 flex items-center gap-1">
                    <Zap className="w-3 h-3" />
                    {user.impactPoints}
                  </span>
                  <span className="text-[9px] text-slate-500 font-medium">pts</span>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

    </div>
  );
}
